# Infinite Bot 3.1.0 - ChatManager(群与游戏消息互通)
#
# 互通支持
# - @: 群内@成员/@全体成员时，若被@者在服务器内且绑定游戏玩家，则游戏中会同样@该玩家
# - 回复: 若被回复QQ绑定玩家且在线，则同样会@该玩家
# - 图片: 该功能需要开启 'expand-chat' 配置节点
#
# 玩家在聊天界面输入 #change
#   切换自身消息接收状态 接收/屏蔽
#
# Notice:
# - 本附属软依赖附属 [ViewManager]: 提供游戏内查看图片支持

# 消息前缀映射配置(仅配置的群可进行消息转发，配置的群无需是机器人管理的群)
#   玩家在游戏中发送 '消息前缀 消息' 即可将消息发送至前缀对应群组，不同群组的前缀可重复
#   例: #main 你好
#   若将消息前缀设为空字符串，则所有公共游戏聊天信息将被转发
#   例: 863522624: ''
prefix-mapper:
  # 群组: 消息前缀
  863522624: '#main'

# 消息互通功能增强
# 开启后，当游戏内发送 InteractiveChat 内配置的展示变量后，自动同步发送至QQ
# 提示：默认展示变量
# - [i] 或 [item], 展示手持物品
# - [inv] 或 [inventory], 展示背包物品
# - [e] 或 [ender], 展示末影箱物品
# 注意：此功能仅在ib3加装 视图增强 附属后且 game-to-group.enable 节点设置为 true 时可用
expand-chat: false

# 群向游戏发送消息配置
group-to-game:
  # 是否开启功能
  enable: true
  # 游戏内接收的消息前缀格式
  # 局部变量
  # - %group_id%: 发送消息的群号
  # - %group_card% 发送消息的群昵称
  # - %sender_id%: 发送消息的用户qq
  # - %sender_card% 发送消息的用户昵称
  # - %sender_name% 发送消息的群名片,失败则用户昵称,还失败则QQ号
  prefix: '(%group_id%) &6&l[&3&l%sender_name%&6&l]&f'
  # 消息发送方式
  # - 'global': 控制台 console 发送消息，不可被屏蔽，
  #             注意：在此方式下消息解析等级始终为 0
  # - 'private': 向各玩家发送私人消息，若玩家设置屏蔽，则不会接受群消息
  type: 'private'
  # 消息解析等级
  # - 0: 仅解析文字，过滤所有其它消息类型
  # - 1: 解析所有支持的消息类型
  parse-level: 1
  # @ 的声音
  # 默认 ENTITY_PLAYER_LEVELUP (高版本), LEVEL_UP (低版本)
  at-sound: ENTITY_PLAYER_LEVELUP
  # 过滤器
  filter:
    # 模式
    # - deny-contains: 包含任意关键字的消息不会被转发
    # - access-start: 仅以关键字开头的消息会被转发
    mode: 'deny-contains'
    # 关键字列表，为空([])则不进行过滤
    key-set: []

# 游戏向群发送消息配置
game-to-group:
  # 是否开启功能
  enable: true
  # 群内接收的消息前缀格式
  # 局部变量
  # - %player_name% 玩家昵称
  prefix: '[测试一服](%player_name%): '
  # 开启异步渲染
  # 注意：异步渲染可能导致部分大图片（如地图）未完全渲染便发出，但异步渲染不会阻塞
  #   主线程，请自行判断是否开启
  async-render: true
  # 过滤器
  filter:
    # 模式
    # - deny-contains: 包含任意关键字的消息不会被转发
    # - access-start: 仅以关键字开头的消息会被转发
    mode: 'access-start'
    # 关键字列表，为空([])则不进行过滤
    key-set: []